name: CI/CD

on: [workflow_call]

jobs:
  vault:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Test code coverage
        run: |
          echo "Testing code coverage"
